drink home page 完成　#8
recursion-team-green1/git-workshop pull request #11
Opened 2022-06-26 04:16 UTC by s1-haya

drink home pageを作成しました。

訂正や改善点があればフィードバックお願いします。

2022-06-26 04:53 UTC, mken816 approved these changes
OKだと思います！

2022-06-26 13:11 UTC, shindo-develop requested changes
index.htmlのナビゲーションバーのリンクの指定のみ、変更した方がいいと思います。

ローカル環境であれば、ローカルホストの127.0.0.1からの絶対パスで指定しても挙動に問題はないのですが、デプロイした際はルートディレクトリがローカルホストではなく、

現在のindex.htmlがある階層がルートディレクトリになるため、相対パスでの指定でないとデプロイ時に404になるかと思います。
`<a href="http://127.0.0.1:5500/git-workshop/index.html" class="nav-link text-dark opacity0q8 ff-italic">Home</a>`

ではなく

`<a href="./index.html" class="nav-link text-dark opacity0q8 ff-italic">Home</a>`
にするといいと思います。


それ以外は問題ないと思います。

2022-06-27 10:55 UTC, mken816 approved these changes

2022-06-27 13:00 UTC, shindo-develop approved these changes

2022-06-27 13:03 UTC, shindo-develop commented
リンクのパスだけ、相対パスへ変更しておいてもらえれば問題ないです。
その他、微細な変更点は挙動に問題なければOKです。

2022-06-27 15:23 UTC, merged